name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Loyiha fayllarini yuklab olish
      uses: actions/checkout@v4

    - name: Java 17 ni o'rnatish
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Ruxsatlarni to'g'rilash
      run: chmod +x ./gradlew

    - name: APK faylni yig'ish (Build)
      run: ./gradlew assembleDebug

    - name: Tayyor APK ni saqlash
      uses: actions/upload-artifact@v4
      with:
        name: SecureMFA-Demo-APK
        path: app/build/outputs/apk/debug/app-debug.apk
